version: 0.0 
os: linux
files:
  - source: / # buildspec.yml에서 생성된 아티팩트 경로에 맞춰 수정
    destination: /home/ubuntu/build/  # 파일을 복사할 대상 경로
    overwrite: yes
  - source: install_java.sh  # install_java.sh 스크립트 복사
    destination: /home/ubuntu/build/  # 스크립트 복사 경로

permissions:  # 파일 권한 설정
  - object: /  # 복사된 파일에 대한 권한 설정
    owner: ubuntu
    group: ubuntu
    mode: 755
    
hooks:
  BeforeInstall:  # Java 설치 스크립트 실행
    - location: install_java.sh  # 스크립트 경로
      timeout: 300
      runas: root

  AfterInstall:  
    - location: start.sh  # 배포 후 실행할 스크립트
      timeout: 60
      runas: ubuntu
