version: 0.0 
os: linux
files:
  - source: /  # Buildspec에서 생성된 아티팩트 경로에 맞게 설정
    destination: /home/ubuntu/build/  # 파일이 복사될 대상 경로
    overwrite: yes

permissions:  
  - object: /home/ubuntu/build/  # 복사된 파일에 대한 권한 설정
    owner: ubuntu
    group: ubuntu
    mode: 755
    
hooks:
  AfterInstall:  
    - location: /home/ubuntu/build/src/start.sh  # start.sh가 복사된 경로
      timeout: 60
      runas: ubuntu
