version: 0.0
os: linux
files:
  - source: src/start.sh  # GitHub에서 src 디렉토리의 start.sh 파일 복사
    destination: /home/ubuntu/build/src/  # EC2 인스턴스의 해당 경로로 복사
    overwrite: yes

permissions:
  - object: /home/ubuntu/build/src/start.sh  # 복사된 파일에 대한 권한 설정
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  BeforeInstall:
    - location: /home/ubuntu/build/src/start.sh  # 필요한 디렉토리 생성 스크립트 추가 가능
      timeout: 60
      runas: ubuntu
  
  AfterInstall:
    - location: /home/ubuntu/build/src/start.sh  # EC2 인스턴스에 복사된 파일 경로
      timeout: 60
      runas: ubuntu
