version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/build/src/ 
    overwrite: yes

permissions:
  - object: /
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  BeforeInstall:
    - location: src/start.sh  # 필요한 디렉토리 생성 스크립트 추가 가능
      timeout: 60
      runas: ubuntu
  
  AfterInstall:
    - location: src/start.sh  # EC2 인스턴스에 복사된 파일 경로
      timeout: 60
      runas: ubuntu
